const easy = [
    {word:'weak' , hint:'lacking the power to perform physically demanding tasks; having little physical strength or energy.' },
    {word:'stay' , hint:'remain in the same place.' },
    {word:'talk' , hint:'speak in order to give information or express ideas or feelings; converse or communicate by spoken words.' },
    {word:'view' , hint:'the ability to see something or to be seen from a particular place.' },
    {word:'user' , hint:'a person who uses or operates something.' },
    {word:'quit' , hint:'leave (a place), usually permanently.' },
    {word:'tool' , hint:'a device or implement, especially one held in the hand, used to carry out a particular function.' },
    {word:'tick' , hint:'a mark (✓) used to indicate that an item in a list or text is correct or has been chosen, checked, or dealt with.' },
    {word:'cake' , hint:'an item of soft sweet food made from a mixture of flour, fat, eggs, sugar, and other ingredients, baked and sometimes iced or decorated.' },
    {word:'flag' , hint:'a piece of cloth or similar material, typically oblong or square, attachable by one edge to a pole or rope and used as the symbol or emblem of a country or institution or as a decoration during public festivities.' },
    {word:'band' , hint:'pass the tongue over (something) in order to taste, moisten, or clean it.' },
    {word:'lick' , hint:'a compact mass of a substance, especially one without a definite or regular shape.' },
    {word:'hook' , hint:'a piece of metal or other hard material curved or bent back at an angle, for catching hold of or hanging things on.' },
    {word:'chew' , hint:'bite and work (food) in the mouth with the teeth, especially to make it easier to swallow.' },
    {word:'pump' , hint:'a mechanical device using suction or pressure to raise or move liquids, compress gases, or force air into inflatable objects such as tyres.' },
    {word:'team' , hint:'a group of players forming one side in a competitive game or sport.' },
    {word:'half' , hint:'either of two equal or corresponding parts into which something is or can be divided.' },
    {word:'glow' , hint:'give out steady light without flame.' },
    {word:'soak' , hint:'make or allow (something) to become thoroughly wet by immersing it in liquid.' },
    {word:'calm' , hint:'not showing or feeling nervousness, anger, or other strong emotions.' },
]
const medium = [
    {word:'carpet' , hint:'a floor covering made from thick woven fabric.' },
    {word:'immune' , hint:'totally or partially resistant to a particular infectious disease or pathogen.' },
    {word:'sermon' , hint:'a talk on a religious or moral subject, especially one given during a church service and based on a passage from the Bible.' },
    {word:'protest' , hint:'a statement or action expressing disapproval of or objection to something.' },
    {word:'labour' , hint:'work, especially physical work.' },
    {word:'ecstasy' , hint:'an overwhelming feeling of great happiness or joyful excitement' },
    {word:'march' , hint:'walk in a military manner with a regular measured tread.' },
    {word:'expose' , hint:'make (something) visible by uncovering it.' },
    {word:'ready' , hint:'in a suitable state for an action or situation; fully prepared.' },
    {word:'jealous' , hint:'feeling or showing an envious resentment of someone or their achievements, possessions, or perceived advantages.' },
    {word:'uniform' , hint:'the distinctive clothing worn by members of the same organization or body or by children attending certain schools.' },
    {word:'bridge' , hint:'a structure carrying a road, path, railway, etc. across a river, road, or other obstacle.' },
    {word:'produce' , hint:'make or manufacture from components or raw materials.' },
    {word:'global' , hint:'relating to the whole world; worldwide.' },
    {word:'density' , hint:'the degree of compactness of a substance.' },
    {word:'archive' , hint:'a collection of historical documents or records providing information about a place, institution, or group of people.' },
    {word:'deliver' , hint:'bring and hand over (a letter, parcel, or goods) to the proper recipient or address.' },
    {word:'eyebrow' , hint:'the strip of hair growing on the ridge above a persons eye socket.' },
    {word:'ceiling' , hint:'the upper interior surface of a room or other similar compartment.' },
    {word:'trivial' , hint:'of little value or importance.' },
]
const hard = [
    {word:'reproduce' , hint:'produce a copy of.' },
    {word:'qualified' , hint:'officially recognized as being trained to perform a particular job; certified.' },
    {word:'technique' , hint:'a way of carrying out a particular task, especially the execution or performance of an artistic work or a scientific procedure.' },
    {word:'assertive' , hint:'having or showing a confident and forceful personality.' },
    {word:'incentive' , hint:'a thing that motivates or encourages someone to do something.' },
    {word:'suspicion' , hint:'a feeling or thought that something is possible, likely, or true.' },
    {word:'satisfied' , hint:'contented; pleased.' },
    {word:'experience' , hint:'practical contact with and observation of facts or events.' },
    {word:'preference' , hint:'a greater liking for one alternative over another or others.' },
    {word:'perception' , hint:'the ability to see, hear, or become aware of something through the senses.' },
    {word:'litigation' , hint:'the process of taking legal action.' },
    {word:'discipline' , hint:'the practice of training people to obey rules or a code of behaviour, using punishment to correct disobedience.' },
    {word:'tournament' , hint:'(in a sport or game) a series of contests between a number of competitors, competing for an overall prize.' },
    {word:'discriminate' , hint:'make an unjust or prejudicial distinction in the treatment of different categories of people, especially on the grounds of ethnicity, sex, age, or disability.' },
    {word:'conservative' , hint:'averse to change or innovation and holding traditional values.' },
    {word:'jurisdiction' , hint:'the official power to make legal decisions and judgements.' },
    {word:'acquaintance' , hint:'knowledge or experience of something.' },
    {word:'battlefield' , hint:'the piece of ground on which a battle is or was fought.' },
    {word:'fluctuation' , hint:'an irregular rising and falling in number or amount; a variation.' },
    {word:'spontaneous' , hint:'performed or occurring as a result of a sudden impulse or inclination and without premeditation or external stimulus.' }
]